"""
Note: This file is generated by ai, with some minor manual tweaks.
It only contains parsing boilerplate.
"""

from pydantic import BaseModel, Field # Import BaseModel and Field

class Coord(BaseModel):
    lon: float
    lat: float

class Weather(BaseModel):
    id: int
    main: str
    description: str
    icon: str

class Main(BaseModel):
    temp: float
    feels_like: float
    temp_min: float
    temp_max: float
    pressure: int
    humidity: int
    sea_level: int | None = None
    grnd_level: int | None = None

class Wind(BaseModel):
    speed: float
    deg: int
    gust: float | None = None

class Rain(BaseModel):
    one_hour: float | None = Field(default=None, alias='1h')

class Clouds(BaseModel):
    all: int

class Sys(BaseModel):
    type: int | None = None
    id: int | None = None
    country: str
    sunrise: int
    sunset: int

class WeatherData(BaseModel): # Inherit from BaseModel
    """Represents the complete weather data object using Pydantic."""
    coord: Coord
    weather: list[Weather]
    base: str
    main: Main
    visibility: int
    wind: Wind
    clouds: Clouds
    dt: int
    sys: Sys
    timezone: int
    id: int
    name: str
    cod: int
    rain: Rain | None = None
